#!/bin/sh

CH340_PRODID="7523"
SYMLINK="arduinoGW"

pID="$(echo $PRODUCT | cut -d '/' -f 2)"

if [ "${pID}" = "${CH340_PRODID}" ]; 
then 
	if [ "${ACTION}" = "add" ]; 
	then 
		DEVICE_NAME=$(ls /sys/$DEVPATH | grep tty) 
		if [ -z ${DEVICE_NAME} ]; 
		then 
			logger -t PERSAVA-HOTPLUG: Warning DEVICE_NAME is empty 
			exit 
		fi 
		logger -t PERSAVA-HOTPLUG: Device name of CH340 is $DEVICE_NAME 
		ln -s /dev/$DEVICE_NAME /dev/${SYMLINK} 
		logger -t PERSAVA-HOTPLUG: Symlink from /dev/$DEVICE_NAME to /dev/${SYMLINK} created 
		screen -XS SERIALSERVICE quit > /dev/null 2>&1
		logger -t PERSAVA-HOTPLUG: serial io service killed
	fi 
fi 

if [ "${pID}" = "${CH340_PRODID}" ]; 
then 
	if [ "${ACTION}" = "remove" ]; 
	then 
		rm /dev/${SYMLINK} 
		logger -t PERSAVA-HOTPLUG: Symlink /dev/${SYMLINK} removed 
	fi 
fi
