#!/bin/sh

FILE=/sys/class/gpio/gpio4/direction
ALARMS=/etc/config/alarms.ini

if test -f "$FILE";
then
	echo "$FILE exists."
else
	echo 4 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio4/direction
	echo 5 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio5/direction
fi

if [[ "$#" -eq 1 ]]
then
	code=$1
	
	dtmfCode="$(cat $ALARMS | grep -w $code | cut -d '=' -f 1)"
	if [[ ! -z "$dtmfCode" ]]
	then
		if [[ "$dtmfCode" == "dtmfCode1" ]]
		then
			action="$(cat $ALARMS | grep -w action1 | cut -d '=' -f 2)"
			duration="$(cat $ALARMS | grep -w duration1 | cut -d '=' -f 2)"
			pin="4"
			
		elif [[ "$dtmfCode" == "dtmfCode2" ]]
		then
			action="$(cat $ALARMS | grep -w action2 | cut -d '=' -f 2)"
			duration="$(cat $ALARMS | grep -w duration2 | cut -d '=' -f 2)"
			pin="5"
		fi
		echo "testts" $pin $action $duration
		if [[ $action == "low" ]]
		then
			echo "l"
			echo 0 > /sys/class/gpio/gpio$pin/value
			sleep $duration
			echo 1 > /sys/class/gpio/gpio$pin/value
		elif [[ $action == "high" ]]
		then
			echo "h"
			echo 1 > /sys/class/gpio/gpio$pin/value
			sleep $duration
			echo 0 > /sys/class/gpio/gpio$pin/value
		elif [[ $action == "toggle" ]]
		then
			echo $pin
			oldVal=$(cat /sys/class/gpio/gpio$pin/value)
			echo $oldVal
			if [[ $oldVal == 0 ]]
			then
				echo 1 > /sys/class/gpio/gpio$pin/value
			else
				echo 0 > /sys/class/gpio/gpio$pin/value
			fi
		fi
		
	fi
else
	pin=$(($1+3))
	action=$2
	duration=$3

	if [[ $action == "l" ]]
	then
		echo "l"
		echo 0 > /sys/class/gpio/gpio$pin/value
		sleep $duration
		echo 1 > /sys/class/gpio/gpio$pin/value
	elif [[ $action == "h" ]]
	then
		echo 1 > /sys/class/gpio/gpio$pin/value
		sleep $duration
		echo 0 > /sys/class/gpio/gpio$pin/value
	elif [[ $action == "t" ]]
	then
		echo $pin
		oldVal=$(cat /sys/class/gpio/gpio$pin/value)
		echo $oldVal
		if [[ $oldVal == 0 ]]
		then
			echo 1 > /sys/class/gpio/gpio$pin/value
		else
			echo 0 > /sys/class/gpio/gpio$pin/value
		fi
	fi
fi
