#!/bin/sh

sipServer="$(cat /etc/config/sipsettings.ini | grep sipServerIp | cut -d '=' -f 2)"
conStat="$(ping -c1 $sipServer > /dev/null && echo UP)"
code="$(cat /etc/config/sipsettings.ini | grep username | cut -d '=' -f 2)"

if [[ ! -z "$conStat" ]]
then
	res="$(curl -sb -H -k https://$sipServer/reporter.php?code=$code)"
	if echo "$res" | grep '404'; then
		regStat="$(echo r | nc 127.0.0.1 5555 | grep sip | grep OK)"
		if [[ -z "$regStat" ]]
		then
			echo "FAIL"
		else
			echo "OK"
		fi
	elif [ -z $res ] ; then
		regStat="$(echo r | nc 127.0.0.1 5555 | grep sip | grep OK)"
		if [[ -z "$regStat" ]]
		then
			echo "FAIL"
		else
			echo "OK"
		fi
	else
		if echo "$res" | grep 'OK'; then
			echo "OK"
		else
			echo "FAIL"
		fi
	fi
else
		echo "FAIL"
fi
